version: '3.8'

services:
  database:
    image: mongo:7.0.12
    container_name: office-mgmt-mongo
    restart: always
    ports:
      - "27018:27017" # Host Port : Container Port
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: